version: "3.8"
services:
  postgres:
    image: postgres:14.2
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - PGSDATA:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    container_name: updateservice
    environment:
      - UPDATE_SRV_DB_CONNECTION_STRING=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - BROKER_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${BROKER_URL}
      - BACKUP_PATH=s3://${MINIO_ROOT_USER}:${MINIO_ROOT_PASSWORD}@minio/backups
      - update_service_SECRET_KEY=${update_service_SECRET_KEY}
      - update_service_MY_ACCESS_KEY=${update_service_MY_ACCESS_KEY} 
      - update_service_MY_SECRET_KEY=${update_service_MY_SECRET_KEY} 
      - update_service_BUCKET_NAME=${update_service_BUCKET_NAME} 
      - update_service_BROKER_URL=${update_service_BROKER_URL} 
      - update_service_ENDPOINT=${update_service_ENDPOINT}
      - update_service_ENDPOINT_LOCAL=${update_service_ENDPOINT_LOCAL} 
    command: sh -c "celery -A updateservice.celeryapp worker --beat --loglevel=info & poe upgrade_heads_dev_container & uvicorn updateservice.app:app --host=0.0.0.0 --port=8080"
    build:
      context: ./
      cache_from:
        - ${IMAGE}
    image: ${IMAGE}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
      - minio


  testdb_postgres:
    image: postgres:14.2
    container_name: testdb_postgresql
    restart: always
    ports:
      - "5434:5434"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: -p 5434


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}


  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address :9001 /data

    volumes:
     - minio_data:/data


volumes:
  PGSDATA:
  minio_data:
